 CLASS zcl_test_cds_booking_000 DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_TEST_CDS_BOOKING_000 IMPLEMENTATION.
ENDCLASS.
